version: '3.5'

networks:
  localdev:
    name: localdev

services:
  main-api:
    build: VocabularyBuilder.API/
    restart: always
    ports:
      - "7000:80"
    depends_on:
      - db-server
    networks:
      - localdev

  deb-server:
    image: microsoft/mssql-server-windows:2017-latest
    container_name: db-server
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=sa
      - MSSQL_TCP_PORT=1433
    ports:
      - "1400:1433"
    networks:
      - localdev